server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    druid:
#      name: frame
      # 连接数据库的url，不同数据库不一样。例如：
      # mysql : jdbc:mysql://ip:port/database
      # oracle : jdbc:oracle:thin:@ip:port:database
#      url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      # 链接数据库的用户名
#      username: root
      # 链接数据库的用户密码，如果你不希望密码直接写在配置文件中，可以使用ConfigFilter。
#      password: 123456
      # 驱动（根据url自动识别）这一项可配可不配，如果不配置druid会根据url自动识别dbType，然后选择相应的driverClassName(建议配置下)
#      driver-class-name: com.mysql.jdbc.Driver
      # 数据库类型
      db-type: com.alibaba.druid.pool.DruidDataSource
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时（缺省值：0）
      initialSize: 1
      # 最大连接池数量（缺省值：8）
      maxActive: 20
      # 最小链接池数量
      minIdle: 1
      # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      maxWait: 60000
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。(缺省值：false)
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-open-prepared-statements: -1
      # 用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validationQuery: select 'x'
      # 检测连接是否有效，配合validationQuery使用，这样配置性能更好
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      # 1) Destroy线程会检测连接的间隔时间2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 物理连接初始化的时候执行的sql
      connectionInitSqls: select 1 from dual
      # 插件： 监控统计用的filter:stat，防御sql注入的filter:wall
      filter:
        # 监控统计
        stat:
          # 数据库类型
          db-type: mysql
          # 慢SQL
          log-slow-sql: true
          # 慢SQL执行时间
          slow-sql-millis: 2000
          # 将同类的SQL合并 例如 select * from table where id = ? ; 如果不配置这个，则不带参数的查询，在druid页面会展示多个
          merge-sql: true
        wall:
          # 开启防止SQL注入
          enabled: true
          db-type: mysql
          # 配置对增删改查的限制，这里不做配置
#          config:
#            delete-allow: false
#            drop-table-allow: false
#            insert-allow: false

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  config: classpath:log4j2_fu.xml

